//! Rust source emission for `crates/ptouch/src/model/generated.rs`.
//!
//! The output is plain, unformatted-but-valid Rust; the caller pipes it through `rustfmt`.
//! Conventions (kept identical to the hand-checked seed): one `static` per media entry named
//! after its id, then `MEDIA`, then `PROFILES`; lengths in tenths of a millimetre
//! (`*_mm_x10`); protocol bytes as `0xNN` hex, USB PIDs as `0xNNNN`; everything else decimal.

use std::fmt::Write as _;

/// `writeln!` into a `String`. `fmt::Write for String` never fails, so the `Result` carries
/// no information and is discarded.
macro_rules! out {
    ($s:expr, $($arg:tt)*) => {{
        let _ = writeln!($s, $($arg)*);
    }};
}

use super::schema::{
    BatteryFormat, BtSocketSecurity, CancelCommand, Compression, Geometry, MediaRow, Meta,
    ModelRow, PageCommand, Table, TapeKind,
};
use super::validate::{mm_x10, static_name, variant_name};

/// Renders the whole file. The table must already have passed validation.
pub fn render(table: &Table) -> Result<String, String> {
    let mut out = String::with_capacity(96 * 1024);
    let s = &mut out;
    s.push_str(HEADER);
    meta(s, &table.meta);
    for m in &table.media {
        media(s, m)?;
    }
    out!(s, "pub(super) static MEDIA: &[&TapeSpec] = &[");
    for m in &table.media {
        out!(s, "    &{},", static_name(&m.id));
    }
    out!(s, "];\n");
    out!(s, "pub(super) static PROFILES: &[ModelProfile] = &[");
    for m in &table.model {
        model(s, m)?;
    }
    out!(s, "];");
    Ok(out)
}

const HEADER: &str = "\
//! Model and media tables generated from `docs/models.toml` (WP1).
//!
//! @generated by `cargo xtask gen-models` — DO NOT EDIT BY HAND.
//!
//! Edit `docs/models.toml` and run `cargo xtask gen-models`; CI runs
//! `cargo xtask gen-models --check` (and the `xtask` tests) to catch drift.

use super::{
    BatteryFormat, BtSocketSecurity, CancelCommand, Caps, Compression, Geometry, Model,
    ModelProfile, PageCommand, Sends, TapeKind, TapeSpec, Transports,
};

";

fn meta(s: &mut String, m: &Meta) {
    out!(s, "/// `meta.usb_vendor_id`.");
    out!(
        s,
        "pub(super) const USB_VENDOR_ID: u16 = {:#06X};",
        m.usb_vendor_id
    );
    out!(s, "/// `meta.usb_out_endpoint`.");
    out!(
        s,
        "pub(super) const USB_OUT_ENDPOINT: u8 = {};",
        hex8(m.usb_out_endpoint)
    );
    out!(s, "/// `meta.usb_in_endpoint`.");
    out!(
        s,
        "pub(super) const USB_IN_ENDPOINT: u8 = {};",
        hex8(m.usb_in_endpoint)
    );
    out!(s, "/// `meta.status_length`.");
    out!(
        s,
        "pub(super) const STATUS_LENGTH: usize = {};",
        m.status_length
    );
    out!(s, "/// `meta.status_header`.");
    let header: Vec<String> = m.status_header.iter().map(|b| hex8(*b)).collect();
    out!(
        s,
        "pub(super) const STATUS_HEADER: [u8; {}] = [{}];",
        m.status_header.len(),
        header.join(", ")
    );
    for (name, key, uuid) in [
        ("SPP_UUID", "spp_uuid", &m.spp_uuid),
        ("BLE_SERVICE_UUID", "ble_service_uuid", &m.ble_service_uuid),
        ("BLE_READ_UUID", "ble_read_uuid", &m.ble_read_uuid),
        ("BLE_WRITE_UUID", "ble_write_uuid", &m.ble_write_uuid),
        (
            "BLE_WRITE_NO_RESPONSE_UUID",
            "ble_write_no_response_uuid",
            &m.ble_write_no_response_uuid,
        ),
        ("BLE_NOTIFY_UUID", "ble_notify_uuid", &m.ble_notify_uuid),
    ] {
        out!(s, "/// `meta.{key}` (lower-cased).");
        out!(
            s,
            "pub(super) const {name}: &str = {:?};",
            uuid.to_ascii_lowercase()
        );
    }
    out!(s, "/// `meta.snmp_status_oid`.");
    out!(
        s,
        "pub(super) const SNMP_STATUS_OID: &str = {:?};\n",
        m.snmp_status_oid
    );
}

fn hex8(b: u8) -> String {
    format!("{b:#04X}").replacen("0X", "0x", 1)
}

fn hex16(v: u16) -> String {
    format!("{v:#06X}").replacen("0X", "0x", 1)
}

fn opt<T>(v: Option<T>, f: impl FnOnce(T) -> String) -> String {
    v.map_or_else(|| "None".to_owned(), |v| format!("Some({})", f(v)))
}

fn geometry(g: Geometry) -> &'static str {
    match g {
        Geometry::Pt128 => "Geometry::Pt128",
        Geometry::Pt3 => "Geometry::Pt3",
        Geometry::Aura64 => "Geometry::Aura64",
        Geometry::Pt560 => "Geometry::Pt560",
    }
}

fn kind(k: TapeKind) -> &'static str {
    match k {
        TapeKind::Tze => "TapeKind::Tze",
        TapeKind::Hs2 => "TapeKind::Hs2",
        TapeKind::Hs3 => "TapeKind::Hs3",
        TapeKind::Sl => "TapeKind::Sl",
        TapeKind::Fle => "TapeKind::Fle",
    }
}

fn media(s: &mut String, m: &MediaRow) -> Result<(), String> {
    let width = mm_x10(m.width_mm, &format!("media {}: width_mm", m.id))
        .and_then(|v| u16::try_from(v).map_err(|e| format!("media {}: width_mm: {e}", m.id)))?;
    out!(
        s,
        "pub(super) static {}: TapeSpec = TapeSpec {{",
        static_name(&m.id)
    );
    out!(s, "    id: {:?},", m.id);
    out!(s, "    geometry: {},", geometry(m.geometry));
    out!(s, "    head_pins: {},", m.head_pins);
    out!(s, "    kind: {},", kind(m.kind));
    out!(s, "    width_mm_x10: {width},");
    out!(s, "    media_width_byte: {},", m.media_width_byte);
    out!(s, "    length_mm: {},", opt(m.length_mm, |v| v.to_string()));
    out!(s, "    status_media_type: {},", hex8(m.status_media_type));
    out!(
        s,
        "    print_info_media_type: {},",
        hex8(m.print_info_media_type)
    );
    out!(
        s,
        "    print_info_media_type_high_res: {},",
        opt(m.print_info_media_type_high_res, hex8)
    );
    out!(s, "    left_margin_pins: {},", m.left_margin_pins);
    out!(s, "    print_pins: {},", m.print_pins);
    out!(s, "    right_margin_pins: {},", m.right_margin_pins);
    out!(s, "    tape_width_dots: {},", m.tape_width_dots);
    out!(s, "    default_feed_dots: {},", m.default_feed_dots);
    out!(
        s,
        "    physical_length_dots: {},",
        opt(m.physical_length_dots, |v| v.to_string())
    );
    out!(
        s,
        "    printable_length_dots: {},",
        opt(m.printable_length_dots, |v| v.to_string())
    );
    out!(s, "}};\n");
    Ok(())
}

fn mm_field<T: TryFrom<u32>>(v: Option<f64>, what: &str) -> Result<Option<T>, String> {
    v.map(|v| {
        mm_x10(v, what)
            .and_then(|x| T::try_from(x).map_err(|_| format!("{what} = {v} is out of range")))
    })
    .transpose()
}

fn model(s: &mut String, m: &ModelRow) -> Result<(), String> {
    let variant = variant_name(&m.name)?;
    let min_len = mm_field::<u16>(m.min_length_mm, &format!("{}: min_length_mm", m.name))?;
    let editor_min = mm_field::<u16>(
        m.editor_min_label_mm,
        &format!("{}: editor_min_label_mm", m.name),
    )?;
    let max_len = mm_field::<u32>(m.max_length_mm, &format!("{}: max_length_mm", m.name))?;
    let strs = |v: &[String]| -> String {
        let items: Vec<String> = v.iter().map(|a| format!("{a:?}")).collect();
        format!("&[{}]", items.join(", "))
    };

    out!(s, "    ModelProfile {{");
    out!(s, "        model: Model::{variant},");
    out!(s, "        name: {:?},", m.name);
    out!(s, "        aliases: {},", strs(&m.aliases));
    out!(s, "        series_code: {},", hex8(m.series_code));
    out!(s, "        model_code: {},", hex8(m.model_code));
    out!(s, "        usb_pid: {},", opt(m.usb_pid, hex16));
    out!(
        s,
        "        transports: Transports {{ bluetooth: {}, ble: {}, network: {} }},",
        m.bluetooth,
        m.ble,
        m.network
    );
    out!(s, "        dpi: {},", m.dpi);
    out!(
        s,
        "        high_res_feed_dpi: {},",
        opt(m.high_res_feed_dpi, |v| v.to_string())
    );
    out!(s, "        head_pins: {},", m.head_pins);
    out!(s, "        bytes_per_line: {},", m.bytes_per_line);
    out!(s, "        max_print_pins: {},", m.max_print_pins);
    out!(s, "        max_tape_mm: {},", m.max_tape_mm);
    out!(s, "        null_bytes: {},", m.null_bytes);
    let page = match m.page_command {
        PageCommand::StartEnd => "PageCommand::StartEnd",
        PageCommand::StartNextEnd => "PageCommand::StartNextEnd",
    };
    out!(s, "        page_command: {page},");
    out!(
        s,
        "        protocol_version: {},",
        opt(m.protocol_version, |v| v.to_string())
    );
    out!(s, "        needs_mode_switch: {},", m.needs_mode_switch);
    out!(
        s,
        "        raster_is_default: {},",
        opt(m.raster_is_default, |v| v.to_string())
    );
    let compression = match m.default_compression {
        Compression::None => "Compression::None",
        Compression::PackBits => "Compression::PackBits",
    };
    out!(s, "        default_compression: {compression},");
    out!(s, "        caps: Caps {{");
    out!(s, "            compression: {},", m.supports_compression);
    out!(s, "            auto_cut: {},", m.supports_auto_cut);
    out!(s, "            cut_mark: {},", m.supports_cut_mark);
    out!(
        s,
        "            cut_every: {},",
        opt(m.supports_cut_every, |v| v.to_string())
    );
    out!(
        s,
        "            chain: {},",
        opt(m.supports_chain, |v| v.to_string())
    );
    out!(s, "            half_cut: {},", m.supports_half_cut);
    out!(s, "            special_tape: {},", m.supports_special_tape);
    out!(s, "            mirror: {},", m.supports_mirror);
    out!(s, "            two_color: {},", m.supports_two_color);
    out!(
        s,
        "            high_resolution: {},",
        m.supports_high_resolution
    );
    out!(s, "            draft: {},", m.supports_draft);
    out!(
        s,
        "            status_notify: {},",
        m.supports_status_notify
    );
    out!(s, "        }},");
    out!(
        s,
        "        special_tape_k: {},",
        opt(m.special_tape_k, hex8)
    );
    out!(s, "        sends: Sends {{");
    out!(
        s,
        "            stored_up_print: {},",
        m.sends_stored_up_print
    );
    out!(s, "            color_info: {},", m.sends_color_info);
    out!(s, "            copies_command: {},", m.sends_copies_command);
    out!(
        s,
        "            mode_reset_at_end: {},",
        m.sends_mode_reset_at_end
    );
    out!(s, "        }},");
    let cancel = match m.cancel_command {
        CancelCommand::EscAt => "CancelCommand::EscAt",
        CancelCommand::EscI18 => "CancelCommand::EscI18",
    };
    out!(s, "        cancel_command: {cancel},");
    let security = opt(m.bt_socket_security, |v| {
        match v {
            BtSocketSecurity::Insecure => "BtSocketSecurity::Insecure",
            BtSocketSecurity::Secure => "BtSocketSecurity::Secure",
        }
        .to_owned()
    });
    out!(s, "        bt_socket_security: {security},");
    out!(
        s,
        "        rfcomm_channel_observed: {},",
        opt(m.rfcomm_channel_observed, |v| v.to_string())
    );
    out!(s, "        min_feed_dots: {},", m.min_feed_dots);
    out!(
        s,
        "        min_length_mm_x10: {},",
        opt(min_len, |v| v.to_string())
    );
    out!(
        s,
        "        editor_min_label_mm_x10: {},",
        opt(editor_min, |v| v.to_string())
    );
    out!(
        s,
        "        max_length_mm_x10: {},",
        opt(max_len, |v| v.to_string())
    );
    let battery = opt(m.battery_format, |v| {
        match v {
            BatteryFormat::Reserved => "BatteryFormat::Reserved",
            BatteryFormat::Legacy => "BatteryFormat::Legacy",
            BatteryFormat::LevelAc => "BatteryFormat::LevelAc",
            BatteryFormat::None => "BatteryFormat::None",
        }
        .to_owned()
    });
    out!(s, "        battery_format: {battery},");
    let media: Vec<String> = m
        .media
        .iter()
        .map(|id| format!("&{}", static_name(id)))
        .collect();
    out!(s, "        media: &[{}],", media.join(", "));
    out!(s, "        quirks: {},", strs(&m.quirks));
    out!(s, "        unknown: {},", strs(&m.unknown));
    out!(s, "    }},");
    Ok(())
}
